## Blood Donation Project

### In this model, we have data of blood transfusions from a mobile donation center in Taiwan, we are trying to predict which individuals donated in March 2007.
### We already have the target values of who donated in March 2007.

In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from collections import Counter
import warnings
warnings.filterwarnings('ignore') 

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('/Users/mahmooooodie/Desktop/DV PROJECTS/Python Practice Project/transfusion.data')
df.head()

Recency (months)  Frequency (times)  Monetary (c.c. blood)  Time (months)  \
0                 2                 50                  12500             98   
1                 0                 13                   3250             28   
2                 1                 16                   4000             35   
3                 2                 20                   5000             45   
4                 1                 24                   6000             77   

   whether he/she donated blood in March 2007  
0                                           1  
1                                           1  
2                                           1  
3                                           1  
4                                           0

In [5]:
df.shape

(748, 5)

In [6]:
new_columns = {
    'Recency (months)':'recency',
    'Frequency (times)': 'frequency',
    'Monetary (c.c. blood)' : 'monetary',
    'Time (months)':'time',
    'whether he/she donated blood in March 2007':'target'   
}
df.rename(columns = new_columns, inplace=True)
df.head()

recency  frequency  monetary  time  target
0        2         50     12500    98       1
1        0         13      3250    28       1
2        1         16      4000    35       1
3        2         20      5000    45       1
4        1         24      6000    77       0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   recency    748 non-null    int64
 1   frequency  748 non-null    int64
 2   monetary   748 non-null    int64
 3   time       748 non-null    int64
 4   target     748 non-null    int64
dtypes: int64(5)
memory usage: 29.3 KB


In [8]:
df.isnull().sum()

recency      0
frequency    0
monetary     0
time         0
target       0
dtype: int64

In [9]:
df.isnull().sum().any()  # checks for any null values at all

False

In [10]:
df.duplicated().sum()

215

In [11]:
df.dtypes

recency      int64
frequency    int64
monetary     int64
time         int64
target       int64
dtype: object

In [12]:
df.describe().T

count         mean          std    min     25%     50%     75%  \
recency    748.0     9.506684     8.095396    0.0    2.75     7.0    14.0   
frequency  748.0     5.514706     5.839307    1.0    2.00     4.0     7.0   
monetary   748.0  1378.676471  1459.826781  250.0  500.00  1000.0  1750.0   
time       748.0    34.282086    24.376714    2.0   16.00    28.0    50.0   
target     748.0     0.237968     0.426124    0.0    0.00     0.0     0.0   

               max  
recency       74.0  
frequency     50.0  
monetary   12500.0  
time          98.0  
target         1.0

In [13]:
df.recency.unique()

array([ 2,  0,  1,  4,  5,  9,  3, 12,  6, 11, 10, 13,  8, 14,  7, 16, 15,
       23, 21, 18, 22, 26, 35, 38, 40, 74, 20, 17, 25, 39, 72])

In [14]:
df.frequency.unique()

array([50, 13, 16, 20, 24,  4,  7, 12,  9, 46, 23,  3, 10,  6,  5, 14, 15,
       11,  8,  2, 19, 17,  1, 22, 18, 38, 43, 34, 44, 26, 41, 21, 33])

In [15]:
df.monetary.unique()

array([12500,  3250,  4000,  5000,  6000,  1000,  1750,  3000,  2250,
       11500,  5750,   750,  2500,  1500,  1250,  3500,  3750,  2750,
        2000,   500,  4750,  4250,   250,  5500,  4500,  9500, 10750,
        8500, 11000,  6500, 10250,  5250,  8250])

In [16]:
df.time.unique()

array([98, 28, 35, 45, 77,  4, 14, 22, 58, 47, 15, 11, 48, 49, 16, 40, 34,
       21, 26, 64, 57, 53, 69, 36,  2, 46, 52, 81, 29,  9, 74, 25, 51, 71,
       23, 86, 38, 76, 70, 59, 82, 61, 79, 41, 33, 10, 95, 88, 19, 37, 39,
       78, 42, 27, 24, 63, 43, 75, 73, 50, 60, 17, 72, 62, 30, 31, 65, 89,
       87, 93, 83, 32, 12, 18, 55,  3, 13, 54])

In [17]:
df['recency'].mean()

9.506684491978609

In [18]:
df['frequency'].max()

50

In [19]:
df['time'].median()

28.0

In [20]:
df['monetary'].std()

1459.826780772503

In [21]:
df['time'].nunique()

78

In [22]:
# ratio of target = 1 to total number of donors
print(df.target.value_counts()[1]/len(df))
print(df.target.value_counts(normalize = True)[1])

0.23796791443850268
0.23796791443850268


In [23]:
df['recency'] < 10

0       True
1       True
2       True
3       True
4       True
       ...  
743    False
744    False
745    False
746    False
747    False
Name: recency, Length: 748, dtype: bool

In [24]:
# filtering recency values less than 10

df[df['recency'] < 10]

recency  frequency  monetary  time  target
0          2         50     12500    98       1
1          0         13      3250    28       1
2          1         16      4000    35       1
3          2         20      5000    45       1
4          1         24      6000    77       0
..       ...        ...       ...   ...     ...
653        4          2       500    30       0
656        4          2       500    31       0
669        2          3       750    75       1
670        2          3       750    77       0
681        4          2       500    46       0

[401 rows x 5 columns]

In [25]:
# Counting how many recency values are less than 10

len(df[df['recency'] < 10])

401

In [26]:
# selecting donors who have donated at least 5 times

len(df[df['frequency'] >=  5])

329

In [27]:
df['timespan'] = df['time'] - df['recency']
df

recency  frequency  monetary  time  target  timespan
0          2         50     12500    98       1        96
1          0         13      3250    28       1        28
2          1         16      4000    35       1        34
3          2         20      5000    45       1        43
4          1         24      6000    77       0        76
..       ...        ...       ...   ...     ...       ...
743       23          2       500    38       0        15
744       21          2       500    52       0        31
745       23          3       750    62       0        39
746       39          1       250    39       0         0
747       72          1       250    72       0         0

[748 rows x 6 columns]

In [30]:
# finding outliers with z scores above 3


from scipy import stats

In [38]:
z_score = np.abs(stats.zscore(df['monetary']))
outliers = np.where(z_score > 2.97)

In [39]:
z_score

0      7.623346
1      1.282738
2      1.796842
3      2.482313
4      3.167784
         ...   
743    0.602307
744    0.602307
745    0.430940
746    0.773675
747    0.773675
Name: monetary, Length: 748, dtype: float64

In [40]:
outliers

(array([  0,   4,   9, 115, 341, 500, 502, 503, 504, 505, 517, 528]),)

In [41]:
df.iloc[outliers]

recency  frequency  monetary  time  target  timespan
0          2         50     12500    98       1        96
4          1         24      6000    77       0        76
9          5         46     11500    98       1        93
115       11         24      6000    64       0        53
341       23         38      9500    98       0        75
500        2         43     10750    86       1        84
502        2         34      8500    77       1        75
503        2         44     11000    98       0        96
504        0         26      6500    76       1        76
505        2         41     10250    98       1        96
517        4         33      8250    98       1        94
528        5         24      6000    79       0        74

In [42]:
df['donorscore'] = (1/df.recency) + df.frequency
df

recency  frequency  monetary  time  target  timespan  donorscore
0          2         50     12500    98       1        96   50.500000
1          0         13      3250    28       1        28         inf
2          1         16      4000    35       1        34   17.000000
3          2         20      5000    45       1        43   20.500000
4          1         24      6000    77       0        76   25.000000
..       ...        ...       ...   ...     ...       ...         ...
743       23          2       500    38       0        15    2.043478
744       21          2       500    52       0        31    2.047619
745       23          3       750    62       0        39    3.043478
746       39          1       250    39       0         0    1.025641
747       72          1       250    72       0         0    1.013889

[748 rows x 7 columns]

In [44]:
df['donorscore1'] = np.where(df.recency == 0, df.frequency, (1/df.recency) + df.frequency )
df.head(5)

recency  frequency  monetary  time  target  timespan  donorscore  \
0        2         50     12500    98       1        96        50.5   
1        0         13      3250    28       1        28         inf   
2        1         16      4000    35       1        34        17.0   
3        2         20      5000    45       1        43        20.5   
4        1         24      6000    77       0        76        25.0   

   donorscore1  
0         50.5  
1         13.0  
2         17.0  
3         20.5  
4         25.0

In [48]:
df['years'] = df.time//12
df['years']

0      8
1      2
2      2
3      3
4      6
      ..
743    3
744    4
745    5
746    3
747    6
Name: years, Length: 748, dtype: int64

In [50]:
df['months'] = df.time % 12
df.head(5)

recency  frequency  monetary  time  target  timespan  donorscore  \
0        2         50     12500    98       1        96        50.5   
1        0         13      3250    28       1        28         inf   
2        1         16      4000    35       1        34        17.0   
3        2         20      5000    45       1        43        20.5   
4        1         24      6000    77       0        76        25.0   

   donorscore1  years  months  
0         50.5      8       2  
1         13.0      2       4  
2         17.0      2      11  
3         20.5      3       9  
4         25.0      6       5

In [53]:
df.corr()['target'].sort_values(ascending = False)

target         1.000000
donorscore1    0.225380
monetary       0.218633
frequency      0.218633
donorscore     0.216745
timespan       0.056986
months        -0.021089
years         -0.032680
time          -0.035854
recency       -0.279869
Name: target, dtype: float64

In [54]:
bins = [0,5,10,50]
groups = ['Low', 'Medium', 'High']
df['freqgroup'] = pd.cut(df['frequency'], bins, labels = groups)
df.sample(5)

recency  frequency  monetary  time  target  timespan  donorscore  \
545        4          2       500     4       1         0    2.250000   
60         2          7      1750    29       0        27    7.500000   
483       23          1       250    23       0         0    1.043478   
412       16          1       250    16       0         0    1.062500   
129        2          2       500    10       1         8    2.500000   

     donorscore1  years  months freqgroup  
545     2.250000      0       4       Low  
60      7.500000      2       5    Medium  
483     1.043478      1      11       Low  
412     1.062500      1       4       Low  
129     2.500000      0      10       Low

In [58]:
df.sample(5)

recency  frequency  monetary  time  target  timespan  donorscore  \
505        2         41     10250    98       1        96   41.500000   
159        2          1       250     2       0         0    1.500000   
577        9          9      2250    38       0        29    9.111111   
521        2         11      2750    41       1        39   11.500000   
348       11          1       250    11       0         0    1.090909   

     donorscore1  years  months freqgroup  
505    41.500000      8       2      High  
159     1.500000      0       2       Low  
577     9.111111      3       2    Medium  
521    11.500000      3       5      High  
348     1.090909      0      11       Low

In [59]:
df.groupby('freqgroup')['monetary'].mean()

freqgroup
Low        624.220374
Medium    1855.182927
High      4143.203883
Name: monetary, dtype: float64

In [61]:
bins = [0,6,12,24,36,74]
groups = ['0-6 m', '6-12 m', '12-24 m', '24-36 m', '36-74']
df['recgroup'] = pd.cut(df['recency'], bins, labels = groups)
df.sample(5)

recency  frequency  monetary  time  target  timespan  donorscore  \
60         2          7      1750    29       0        27    7.500000   
647        2          2       500    33       0        31    2.500000   
638       11          4      1000    27       0        16    4.090909   
422       21          2       500    23       0         2    2.047619   
216        4          1       250     4       0         0    1.250000   

     donorscore1  years  months freqgroup recgroup  
60      7.500000      2       5    Medium    0-6 m  
647     2.500000      2       9       Low    0-6 m  
638     4.090909      2       3       Low   6-12 m  
422     2.047619      1      11       Low  12-24 m  
216     1.250000      0       4       Low    0-6 m

In [62]:
df.target.value_counts(normalize = True).round(3)

0    0.762
1    0.238
Name: target, dtype: float64

In [63]:
output_data = []

for col in df.columns:
    
    # If the number of unique values in the column is less than or equal to 5
    if df.loc[:, col].nunique() <= 5:
        # Get the unique values in the column
        unique_values = df.loc[:, col].unique()
        # Append the column name, number of unique values, unique values, and data type to the output data
        output_data.append([col, df.loc[:, col].nunique(), unique_values, df.loc[:, col].dtype])
    else:
        # Otherwise, append only the column name, number of unique values, and data type to the output data
        output_data.append([col, df.loc[:, col].nunique(),"-", df.loc[:, col].dtype])

output_df = pd.DataFrame(output_data, columns=['Column Name', 'Number of Unique Values', ' Unique Values ', 'Data Type'])

output_df

Column Name  Number of Unique Values  \
0       recency                       31   
1     frequency                       33   
2      monetary                       33   
3          time                       78   
4        target                        2   
5      timespan                       90   
6    donorscore                      184   
7   donorscore1                      186   
8         years                        9   
9        months                       12   
10    freqgroup                        3   
11     recgroup                        5   

                                       Unique Values  Data Type  
0                                                   -     int64  
1                                                   -     int64  
2                                                   -     int64  
3                                                   -     int64  
4                                              [1, 0]     int64  
5                                                   -     int64  
6                                                   -   float64  
7                                                   -   float64  
8                                                   -     int64  
9                                                   -     int64  
10  ['High', 'Low', 'Medium']
Categories (3, objec...  category  
11  ['0-6 m', NaN, '6-12 m', '12-24 m', '24-36 m',...  category

In [64]:
def grab_col_names(dataframe, cat_th=10):

    # cat_cols
    cat_cols = [col for col in dataframe.columns if dataframe[col].dtypes == "O"]
    num_but_cat = [col for col in dataframe.columns if dataframe[col].nunique() < cat_th and
                   dataframe[col].dtypes != "O"]    
    cat_cols = cat_cols + num_but_cat
    

    # num_cols
    num_cols = [col for col in dataframe.columns if dataframe[col].dtypes != "O"]
    num_cols = [col for col in num_cols if col not in cat_cols]

    print(f"Features: {dataframe.shape[1]}")
    print(f'Number of Categorical Features: {len(cat_cols)}')
    print(f'Number of Numeric Features: {len(num_cols)}')
    print(f"Categorical Features: {cat_cols}") 
    print(f"Numeric Features: {num_cols}")
    
    return cat_cols, num_cols

In [65]:
cat_cols, num_cols = grab_col_names(df)

Features: 12
Number of Categorical Features: 4
Number of Numeric Features: 8
Categorical Features: ['target', 'years', 'freqgroup', 'recgroup']
Numeric Features: ['recency', 'frequency', 'monetary', 'time', 'timespan', 'donorscore', 'donorscore1', 'months']


In [66]:
def summary(df, pred=None):
    obs = df.shape[0]
    Types = df.dtypes
    Counts = df.apply(lambda x: x.count())
    Min = df.min()
    Max = df.max()
    Uniques = df.apply(lambda x: x.unique().shape[0])
    Nulls = df.apply(lambda x: x.isnull().sum())
    print('Data shape:', df.shape)

    if pred is None:
        cols = ['Types', 'Counts', 'Uniques', 'Nulls', 'Min', 'Max']
        str = pd.concat([Types, Counts, Uniques, Nulls, Min, Max], axis = 1, sort=True)

    str.columns = cols
    print('___________________________\nData Types:')
    print(str.Types.value_counts())
    print('___________________________')
    return str

summary(df)

Data shape: (748, 12)
___________________________
Data Types:
int64       8
float64     2
category    1
category    1
Name: Types, dtype: int64
___________________________


Types  Counts  Uniques  Nulls       Min    Max
donorscore    float64     748      184      0  1.013514    inf
donorscore1   float64     748      186      0  1.013514   50.5
freqgroup    category     748        3      0       Low   High
frequency       int64     748       33      0         1     50
monetary        int64     748       33      0       250  12500
months          int64     748       12      0         0     11
recency         int64     748       31      0         0     74
recgroup     category     743        6      5     0-6 m  36-74
target          int64     748        2      0         0      1
time            int64     748       78      0         2     98
timespan        int64     748       90      0         0     96
years           int64     748        9      0         0      8

In [67]:
def duplicate_values(df):
    print("Duplicate check...")
    num_duplicates = df.duplicated(subset=None, keep='first').sum()
    if num_duplicates > 0:
        print("There are", num_duplicates, "duplicated observations in the dataset.")
        df.drop_duplicates(keep='first', inplace=True)
        print(num_duplicates, "duplicates were dropped!")
        print('*' * 100)
    else:
        print("There are no duplicated observations in the dataset.")

In [68]:
duplicate_values(df)

Duplicate check...
There are 215 duplicated observations in the dataset.
215 duplicates were dropped!
****************************************************************************************************


In [69]:
duplicate_values(df)

Duplicate check...
There are no duplicated observations in the dataset.


In [70]:
def missing_values(df):
    missing_number = df.isnull().sum().sort_values(ascending = False)
    missing_percent = (df.isnull().sum() / df.isnull().count()).sort_values(ascending = False)
    missing_values = pd.concat([missing_number, missing_percent], axis = 1, keys = ['Missing_Number', 'Missing_Percent'])
    return missing_values[missing_values['Missing_Number'] > 0]

In [71]:
missing_values(df)

Missing_Number  Missing_Percent
recgroup               5         0.009381

In [72]:
def value_cnt(df, column_name):
    vc = df[column_name].value_counts()
    vc_norm = df[column_name].value_counts(normalize=True).round(3)

    vc = vc.rename_axis('workclass').reset_index(name='counts')
    vc_norm = vc_norm.rename_axis('workclass').reset_index(name='norm_counts')

    df_result = pd.concat([vc['workclass'], vc['counts'], vc_norm['norm_counts']], axis=1)
    
    return df_result

In [74]:
# Target görülme sıklığı, bir veri kümesindeki her bir Target değerin vaka sayısı olarak tanımlanır.
# Yani Target sütunda kaç tane 1'e karşılık kaç tane 0 var? 
# Target insidansı bize veri setimizin ne kadar dengeli (veya dengesiz) olduğuna dair bir fikir verir.

value_cnt(df, 'target')

workclass  counts  norm_counts
0          0     384         0.72
1          1     149         0.28